name: "GuFi Software"
description: "En produkt från GuFi Enterprise"
url: "https://github.com/urbaxe/GuFi"
webui: "http://ha.fixdata.ws:8000"
maintainer: "The GuFi-Team"
version: "1.1.4f"
slug: "hello_world"
arch:
  - amd64
init: false
ports:
  8000/tcp: 8000
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2022
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
